export const casasData: Casa[] = [
    {
        id: '1',
        // title: 'Casa con Jardín Encantador',
        tipo: 'alquiler',
        zona: 'Madrid',
        descripcion: 'Hermosa casa con jardín privado y diseño moderno',
        num_dormitorios: 4,
        num_banios: 2,
        superficie: 250,
        precio: 750000,
        imagen: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/286068026.jpg?k=28779c87c98f4f970050611d5b6c24563c0084899dc149ca04ad84c4a3ff09a9&o=&hp=1',
        estado: 'nuevo',
        amoblado: true,
        garaje: false,
        patio: true,
        tiene_sotano: false,
    },
    {
        id: '2',
        // title: 'Apartamento Moderno Centro',
        tipo: 'anticretico',
        zona: 'Barcelona',
        descripcion: 'Apartamento contemporáneo en zona céntrica',
        num_dormitorios: 3,
        num_banios: 2,
        superficie: 120,
        precio: 550000,
        imagen: 'https://i.ytimg.com/vi/eRe0DZb-RgQ/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBRHYfNMB4OWCOqkjTZVwGWMiEsQg',
        estado: 'oferta',
        amoblado: true,
        garaje: true,
        patio: true,
        tiene_sotano: true
    },
    {
        id: '3',
        // title: 'Casa Familiar Espaciosa',
        tipo: 'venta',
        zona: 'Valencia',
        descripcion: 'Vivienda ideal para familias grandes con amplio terreno',
        num_dormitorios: 5,
        num_banios: 3,
        superficie: 350,
        precio: 900000,
        imagen: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&h=300&fit=crop',
        estado: 'nuevo',
        amoblado: false,
        garaje: false,
        patio: true,
        tiene_sotano: true
    },
    {
        id: '4',
        // title: 'Condominio Acogedor',
        tipo: 'venta',
        zona: 'Sevilla',
        descripcion: 'Departamento acogedor en residencia segura',
        num_dormitorios: 2,
        num_banios: 1,
        superficie: 80,
        precio: 350000,
        imagen: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
        estado: 'oportunidad',
        amoblado: false,
        garaje: false,
        patio: true,
        tiene_sotano: true
    },
    {
        id: '5',
        // title: 'Villa Moderna en la Playa',
        tipo: 'venta',
        zona: 'Málaga',
        descripcion: 'Espectacular villa con vistas al mar y piscina',
        num_dormitorios: 4,
        num_banios: 3,
        superficie: 300,
        precio: 1200000,
        imagen: 'https://media.vrbo.com/lodging/19000000/18970000/18967500/18967480/f40d1f3b.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill',
        estado: 'nuevo',
        amoblado: false,
        garaje: false,
        patio: true,
        tiene_sotano: true
    },
    {
        id: '6',
        // title: 'Piso Céntrico Reformado',
        tipo: 'alquiler',
        zona: 'Madrid',
        descripcion: 'Cass pequeña  con acabados premium',
        num_dormitorios: 2,
        num_banios: 2,
        superficie: 100,
        precio: 450000,
        imagen: 'https://s.alicdn.com/@sc04/kf/H1b7cdab79bc149fdbf10c34263ac9922p/Prefabricate-2-Bedroom-Luxury-Design-Ready-Made-Wooden-Modern-Small-Casas-Prefab-SIP-Light-Steel-Tiny-House-Modular-Home-Villa.jpg_300x300.jpg',
        estado: 'oferta',
        amoblado: false,
        garaje: false,
        patio: true,
        tiene_sotano: true
    }
]