export const casasData: Casa[] = [
    {
        id: '1',
        tipo: 'venta',
        zona: 'Zona Norte - Queru Queru',
        descripcion: 'Hermosa casa con jardín amplio y diseño moderno en la zona norte, cerca del Huper Mall',
        num_dormitorios: 4,
        num_banios: 3,
        superficie: 320,
        precio: 185000,
        imagen: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/286068026.jpg?k=28779c87c98f4f970050611d5b6c24563c0084899dc149ca04ad84c4a3ff09a9&o=&hp=1',
        estado: 'nuevo',
        amoblado: true,
        tipoPropiedad: 'Casa', 
        garaje: true,
        patio: true,
        tiene_sotano: false,
    },
    {
        id: '2',
        tipo: 'venta',
        zona: 'Zona Cala Cala',
        tipoPropiedad: 'Departamento', 
        descripcion: 'Departamento moderno con excelente vista, ubicado en un edificio exclusivo de Cala Cala',
        num_dormitorios: 3,
        num_banios: 2,
        superficie: 140,
        precio: 150000,
        imagen: 'https://i.ytimg.com/vi/eRe0DZb-RgQ/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBRHYfNMB4OWCOqkjTZVwGWMiEsQg',
        estado: 'oferta',
        amoblado: true,
        garaje: true,
        patio: false,
        tiene_sotano: true
    },
    {
        id: '3',
        tipo: 'venta',
        zona: 'Zona Tiquipaya',
        descripcion: 'Casa amplia ideal para familias grandes, rodeada de áreas verdes y con terreno extenso',
        num_dormitorios: 5,
        num_banios: 4,
        tipoPropiedad: 'Casa', 
        superficie: 380,
        precio: 210000,
        imagen: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&h=300&fit=crop',
        estado: 'nuevo',
        amoblado: false,
        garaje: true,
        patio: true,
        tiene_sotano: false
    },
    {
        id: '4',
        tipo: 'venta',
        zona: 'Zona Sud - Jaihuayco',
        descripcion: 'Casa cómoda en zona tranquila y residencial, ideal para una familia pequeña',
        num_dormitorios: 2,
        num_banios: 1,
        superficie: 95,
        precio: 80000,
        imagen: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
        estado: 'oportunidad',
        amoblado: false,
        tipoPropiedad: 'Casa', 
        garaje: false,
        patio: true,
        tiene_sotano: false
    },
    {
        id: '5',
        tipo: 'venta',
        zona: 'Zona Norte - Colcapirhua',
        descripcion: 'Villa moderna con piscina y acabados de lujo, ubicada en una zona tranquila de Colcapirhua',
        num_dormitorios: 4,
        tipoPropiedad: 'Casa', 
        num_banios: 3,
        superficie: 310,
        precio: 240000,
        imagen: 'https://media.vrbo.com/lodging/19000000/18970000/18967500/18967480/f40d1f3b.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill',
        estado: 'nuevo',
        amoblado: true,
        garaje: true,
        patio: true,
        tiene_sotano: true
    },
    {
        id: '6',
        tipo: 'alquiler',
        zona: 'Zona Este - Villa Busch',
        descripcion: 'Casa pequeña con dos dormitorios, patio y cocina moderna, cerca del Parque Mariscal Santa Cruz',
        num_dormitorios: 2,
        tipoPropiedad: 'Casa', 
        num_banios: 2,
        superficie: 110,
        precio: 600,
        imagen: 'https://s.alicdn.com/@sc04/kf/H1b7cdab79bc149fdbf10c34263ac9922p/Prefabricate-2-Bedroom-Luxury-Design-Ready-Made-Wooden-Modern-Small-Casas-Prefab-SIP-Light-Steel-Tiny-House-Modular-Home-Villa.jpg_300x300.jpg',
        estado: 'oferta',
        amoblado: false,
        garaje: false,
        patio: true,
        tiene_sotano: false
    }
]
